polling_project/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls')),
    path('polls/', include('polls.urls')),
    path('api/', include('polls.api.urls')),
    path('spyne/', include('polls.spyne.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('__debug__/', include(debug_toolbar.urls)),
]

# added for testing otherwise static files should be server from ngnix
urlpatterns += staticfiles_urlpatterns()

polls/api/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = "api"

router = routers.SimpleRouter()
router.register(r"polls", views.PollViewSet, basename="poll")
router.register(r"votes", views.VoteViewSet, basename="vote")

urlpatterns = [
    path("", views.api_root),
    path("categories/", views.CategoryViewApi.as_view(), name="categories-list"),
]

urlpatterns += router.urls

polls/spyne/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url("question_interface/", views.question_interface),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/comments/", views.CommentView.as_view(), name="comments"),
    path("create/", views.CreatePollView.as_view(), name="create"),
    path("<int:question_id>/edit/", views.EditPollView.as_view(), name="edit"),
    path("history/", views.HistoryView.as_view(), name="history"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.RegisterUserView.as_view(), name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

polls/forms.py
from django import forms
from django.utils import timezone

from .models import Category, Choice, Comment, Question, Vote


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["question_text", "category"]

    question_text = forms.CharField(label="Question/Topic")

    category = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    def save(self, commit=True, user=None):
        question = super(QuestionForm, self).save(commit=False)
        question.pub_date = timezone.now()
        question.author = user
        if question:
            question.save()
        return question


class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ["choices"]

    choices = forms.ChoiceField(
        widget=forms.RadioSelect, choices=[], label="Vote Your Choice", required=True
    )

    def __init__(self, *args, **kwargs):
        self.question = kwargs["initial"]["question"]
        self.user = kwargs["initial"]["user"]
        super(VoteForm, self).__init__(*args, **kwargs)
        choice_list = [
            (choice.id, choice.choice_text) for choice in self.question.choice_set.all()
        ]
        self.fields["choices"].choices = choice_list
        if self.user.is_authenticated:
            vote = self.user.vote_set.filter(question=self.question).first()
            selected_choice_id = vote.choice_id if vote is not None else None
            self.fields["choices"].initial = selected_choice_id


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]

polls/api/views.py
from django.db.models import Count
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from rest_framework import generics, permissions, viewsets
from rest_framework.decorators import action, api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse

from polls.models import Category, Question, Vote

from .permissions import IsAuthorOrReadOnly, ResultPermission
from .serializers import (CategorySerializer, PollResultSerializer,
                          QuestionSerializer, VoteSerializer)


class PollViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.default_api_list_query()
    serializer_class = QuestionSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsAuthorOrReadOnly]

    @action(
        detail=True,
        methods=["get"],
        permission_classes=[permissions.IsAuthenticated, ResultPermission],
    )
    def result(self, request, *args, **kwargs):
        serializer = PollResultSerializer(
            self.get_object(), context={"request": request}
        )
        return Response(serializer.data)


class VoteViewSet(viewsets.ModelViewSet):
    permission_classes = [permissions.IsAuthenticated]
    serializer_class = VoteSerializer

    def get_queryset(self):
        return Vote.objects.filter(voter=self.request.user).order_by("-updated_at")


class CategoryViewApi(generics.ListAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

    """ API response will be cached for 1 minute """

    @method_decorator(cache_page(timeout=60))
    def dispatch(self, *args, **kwargs):
        return super(CategoryViewApi, self).dispatch(*args, **kwargs)


@api_view(["GET"])
def api_root(request, format=None):
    return Response(
        {
            "polls": reverse("api:poll-list", request=request, format=format),
            "user-vote": reverse("api:vote-list", request=request, format=format),
            "categories_list": reverse(
                "api:categories-list", request=request, format=format
            ),
        }
    )

polls/spyne/views.py
from django.views.decorators.csrf import csrf_exempt
from spyne import Application, ServiceBase, Unicode, rpc
from spyne.model.complex import Array, ComplexModel, Iterable
from spyne.model.primitive import AnyDict, DateTime, Integer
from spyne.protocol.soap import Soap11
from spyne.server.django import DjangoApplication

from polls.api.serializers import QuestionSerializer
from polls.models import Category, Choice, Question


class QuestionModel(ComplexModel):
    id = Integer
    author_id = Integer
    question_text = Unicode
    pub_date = DateTime

    @classmethod
    def init_from_db_record(cls, model):
        obj = cls()
        obj.id = model.id
        obj.author_id = model.author_id
        obj.question_text = model.question_text
        obj.pub_date = model.pub_date
        return obj


class QuestionInterface(ServiceBase):
    @rpc(_returns=Iterable(QuestionModel))
    def getQuestionList(self):
        question = Question.objects.all()
        for q in question:
            yield QuestionModel.init_from_db_record(q)

    @rpc(Integer, _returns=QuestionModel)
    def fetchQuestion(self, id):
        question = Question.objects.get(id=id)
        return QuestionModel.init_from_db_record(question)

    @rpc(QuestionModel, _returns=QuestionModel)
    def createQuestion(self, question_data):
        que = Question()
        que.author_id = question_data.author_id
        que.question_text = question_data.question_text
        que.pub_date = question_data.pub_date
        que.save()
        return QuestionModel.init_from_db_record(que)

    @rpc(QuestionModel, _returns=QuestionModel)
    def updateQuestion(self, question_data):
        que = Question.objects.get(id=question_data.id)
        que.question_text = question_data.question_text
        que.pub_date = question_data.pub_date
        que.save()
        return QuestionModel.init_from_db_record(que)

    @rpc(Integer, _returns=Unicode)
    def deleteQuestion(self, id):
        question = Question.objects.get(id=id)
        question.delete()
        return "Deleted Object"


application = Application(
    [QuestionInterface],
    tns="http://schemas.xmlsoap.org/soap/envelope/",
    in_protocol=Soap11(),
    out_protocol=Soap11(),
)

question_interface = csrf_exempt(DjangoApplication(application))

polls/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.db.models import Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View, generic
from django.views.generic.edit import FormMixin

from .decorators import set_question_and_verify_author
from .forms import CommentForm, QuestionForm, VoteForm
from .models import Category, Choice, Comment, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"

    def get_queryset(self):
        """Return the last five published questions."""
        queryset = Question.objects.default_list_query()
        
        category_id = self.request.GET.get("category")
        if category_id:
            queryset = queryset.filter_by_category(category_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        extra_context = {
            "category_list_data": Category.get_list(),
        }
        context.update(extra_context)
        return context


class DetailView(FormMixin, generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    form_class = VoteForm

    # This will pass to the form_class on initalization
    def get_initial(self):
        return {"question": self.get_object(), "user": self.request.user}


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


class HistoryView(LoginRequiredMixin, generic.ListView):
    template_name = "polls/history.html"
    login_url = "user:login"

    def get_queryset(self):
        """Return the list of polls in which user have participated"""
        return Question.objects.default_list_query().filter_user_voted_question(self.request.user.id)


class CreatePollView(LoginRequiredMixin, View):
    login_url = "user:login"

    def get(self, request):
        question_form = QuestionForm()
        choice_form = inlineformset_factory(
            Question, Choice, fields=("choice_text",), extra=4
        )
        context = {
            "question_form": question_form,
            "choice_form": choice_form,
            "action": "Create",
        }
        return render(request, "polls/poll_form.html", context)

    def post(self, request):
        question_form = QuestionForm(request.POST)
        choice_form = inlineformset_factory(
            Question, Choice, fields=("choice_text",), extra=4
        )
        if question_form.is_valid():
            with transaction.atomic():
                question = question_form.save(user=request.user)
                question.category_set.add(*question_form.cleaned_data["category"])
                choice_form = choice_form(request.POST, instance=question)
                assert choice_form.is_valid(), "Form Invalid!"
                choices = choice_form.save()
            messages.success(self.request, "Poll Created")
            return redirect("polls:detail", question.id)
        else:
            messages.error(self.request, "Error Occured")
            context = {
                "question_form": question_form,
                "choice_form": choice_form,
                "action": "Create",
            }
            return render(request, "polls/poll_form.html", context)


class EditPollView(LoginRequiredMixin, View):
    login_url = "user:login"

    @method_decorator(set_question_and_verify_author)
    def get(self, request, question_id, question=None):
        question_form = QuestionForm(
            instance=question, initial={"category": question.category_set.all()}
        )
        ChoiceForm = inlineformset_factory(
            Question, Choice, fields=("choice_text",), extra=0
        )
        choice_form = ChoiceForm(instance=question)
        context = {
            "question_form": question_form,
            "choice_form": choice_form,
            "action": "Update",
        }
        return render(request, "polls/poll_form.html", context)

    @method_decorator(set_question_and_verify_author)
    def post(self, request, question_id, question=None):
        question_form = QuestionForm(request.POST, instance=question)
        ChoiceForm = inlineformset_factory(Question, Choice, fields=("choice_text",))
        choice_form = ChoiceForm(request.POST, instance=question)
        if question_form.is_valid() and choice_form.is_valid():
            with transaction.atomic():
                question = question_form.save(user=request.user)
                choices = choice_form.save()
                question.category_set.clear()
                question.category_set.add(*question_form.cleaned_data["category"])
            messages.success(self.request, "Poll Updated")
            return redirect("polls:detail", question.id)
        else:
            messages.error(self.request, "Error Occured")
            context = {
                "question_form": question_form,
                "choice_form": choice_form,
                "action": "Update",
            }
            return render(request, "polls/poll_form.html", context)


class CommentView(generic.CreateView):
    form_class = CommentForm
    template_name = "polls/comment_list.html"

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.commenter_id = self.request.user.id
        obj.question_id = self.kwargs.get("question_id")
        obj.save()
        messages.success(self.request, "Comment added")
        return redirect("polls:detail", self.kwargs.get("question_id"))

    def get_context_data(self, **kwargs):
        context = super(CommentView, self).get_context_data(**kwargs)
        extra_context = {
            "comment_list": Comment.objects.filter(
                question_id=self.kwargs.get("question_id")
            )
            .select_related("commenter")
            .order_by("created_at")
            .only("id", "comment_text", "created_at", "commenter__username"),
            "question_id": self.kwargs.get("question_id"),
        }
        context.update(extra_context)
        return context


@login_required(login_url="user:login", redirect_field_name=None)
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    vote_form = VoteForm(
        request.POST, initial={"question": question, "user": request.user}
    )
    if vote_form.is_valid():
        vote, created = request.user.vote_set.update_or_create(
            question=question, defaults={"choice_id": vote_form.cleaned_data["choices"]}
        )
        messages.success(request, "Successfully Voted" if created else "Vote Updated")
    else:
        messages.error(request, "Something wend wrong.")
    return redirect("polls:results", question.id)

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title> Polling Project {% block title_heading %}{% endblock title_heading %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/790a4728d4.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <!-- Brand/logo -->
      <!-- <a class="navbar-brand" href="">Polling Project</a> -->
      
      <!-- Links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'polls:index' %}"> <i class="fas fa-home"></i> Home</a>
        </li>
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:history'%}"> <i class="fas fa-poll"></i> History</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'polls:create'%}"> <i class="fas fa-plus-circle"></i>  Create a poll</a>
          </li>
        {% endif %}
      </ul>

      <div class="ml-md-auto">
        {% if request.user.is_authenticated %}
          <a href="{% url 'user:logout' %}">
            <button class="btn btn-danger"> Logout </button>
          </a>
        {% else %}
          <a href="{% url 'user:register' %}">
            <button class="btn btn-success"> Register </button>
          </a> 
          <a href="{% url 'user:login' %}">
            <button class="btn btn-success"> Login </button>
          </a> 
        {% endif %}
      </div>
    </nav>
  </header>
  <div class="container">
    <br>
    {% block content %}{% endblock content %}
  </div>
  <footer></footer>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
    $(document).ready(function() {
      {% if messages %}
        {% for message in messages %}
          toastr.{{message.tags}}('{{ message|safe }}')
        {% endfor %}
      {% endif %}
    });
  </script>
</body>
</html>

polls/templates/polls/comment_list.html
{% load crispy_forms_tags %}
{% if request.user.is_authenticated %}
    <b> Write your thoughts </b>
    <form method="post" action="{% url 'polls:comments' question_id%}" id="comment-form">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-primary" value="Post Comment">
    </form>
    <br/>
{% endif %}
<div class="comments">
    <b> Comments : </b> <br>
    {% if comment_list %}
        {% for comment in comment_list %}
            <p>
                <b>{{ comment.commenter.username }} : </b> {{ comment.comment_text }}
            </p>
        {% endfor %}
    {% else %}
        There are no comments for this poll yet.
    {% endif %}
</div>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}
{% load common_tags %}

{% block title_heading %}
  | Poll
{% endblock %}
{% block content %} 
    <br/>
    <form action="{% url 'polls:vote' question.id %}" method="post" class="container">
        {% csrf_token %}
        <div class="card">
            <div class="card-header">
                <b>{{question.question_text}}</b><br/>
                {% print_question_category question %}
            </div>
            <div class="card-body">{{ form|crispy }}</div>
            <div class="card-footer">
                <input type="submit" value="Vote" class="btn btn-primary">
                {% if request.user == question.author %}
                    <a href="{% url 'polls:edit' question.id %}"class="btn btn-secondary"> Edit Question </a>
                {% endif %}
            </div>
        </div>     
    </form>

    <br/><br/>
    <div class="comment_section container"></div>

    <script>
        $(document).ready(function(){
            $.get( "{% url 'polls:comments' question.id %}", function( data ) {
              $( ".comment_section" ).html( data );
            });
        })
    </script>
{% endblock %}

polls/templates/polls/history.html
{% extends "polls/base.html" %}
{% load common_tags %}

{% block title_heading %}
  | Voting History
{% endblock %}

{% block content %} 
    <h2>History</h2>
    {% if question_list %}
        {% for question in question_list %}
            <br/>
            <a href="{% url 'polls:detail' question.id %}" class="text-dark" style="text-decoration: none;">
                <div class="card">
                    <div class="card-body">
                        <b>{{question.question_text}}</b><br/>
                        {% print_question_category question %}
                    </div>
                    <div class="card-footer"> Vote: {{ question.vote__count }}</div>
                </div>
            </a>
        {% endfor %}
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}
{% load common_tags %}

{% block title_heading %}
  | Home
{% endblock %}

{% block content %}
    <h2>All Question</h2>
    <div class="row">
        <div class="col-sm-9"> 
            {% if question_list %}
                {% for question in question_list %}
                    <br/>
                    <a href="{% url 'polls:detail' question.id %}" class="text-dark" style="text-decoration: none;">
                        <div class="card question" data-question={{question.id}}>
                            <div class="card-body"> 
                                <b>{{question.question_text}}</b><br/>
                                {% print_question_category question %}
                            </div>
                            <div class="card-footer">
                                <span id="question_vote_count_{{question.id}}">
                                    Vote: {{ question.vote__count }}
                                </span>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
        </div>
        <div class="col-sm-3">
            <br/>
            <div class="card">
                <div class="card-header"> <b> Category Filter </b> </div>
                <ul class="list-group">
                    {%  for category in category_list_data %}
                        <a href="{% url 'polls:index' %}?category={{category.0}}" style="text-decoration: none;" class="text-dark">
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                            <b> {{ category.1 }} </b>
                            <!-- <span class="badge badge-primary badge-pill">12</span> -->
                            </li>
                        </a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <script>
        $(document).ready(function(){
            const question_list = $('.question').map(function(){
                return $(this).data('question');
            }).get()
            const ws_connection_list = question_list.map(id => connect_question_with_channel(id))
        })

        function connect_question_with_channel(id){
            url = 'ws://localhost:8001/ws/question/'+id+'/'

            const chatSocket = new WebSocket(url)

            chatSocket.onmessage = function(e) {
                const data = JSON.parse(e.data);
                text = "Vote : "+ data.message.vote_count
                $("#question_vote_count_"+id).text(text)
            };
            chatSocket.onclose = function(e) { console.log(e) }
        }
    </script>

{% endblock %}

polls/templates/polls/poll_form.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}

{% block title_heading %}
  | Create Poll
{% endblock %}

{% block content %} 
  <form method="POST" class="slim_form">
    {% csrf_token %}
    <div class="card">
      <div class="card-header">
        <b> {{ action }} Poll Form </b>
      </div>
      <div class="card-body">
        {{ question_form|crispy }} 
        {{ choice_form|crispy }}
      </div>
    <div class="card-footer">                    
      <button class="btn btn-primary" type="submit">{{ action }} Poll</button>
    </div>
  </form>
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}
{% load crispy_forms_tags %}

{% block title_heading %}
  | Result
{% endblock %}
{% block content %} 
    <br/>
    <div class="card">
        <div class="card-header"><b>{{question.question_text}}</b></div>
        <div class="card-body">
            <ul>
                {% for choice in question.choice_set.all %}
                    <li>{{ choice.choice_text }} -- {{ choice.count_total_votes }} vote{{ choice.votes|pluralize }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-footer"><a href="{% url 'polls:detail' question.id %}" class="btn btn-primary">Change your vote?</a></div>
    </div>     
{% endblock %}